# Generated by Django 4.1.7 on 2023-03-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediauser',
            name='image_url',
            field=models.CharField(default='', max_length=500, verbose_name='Profile Url'),
        ),
        migrations.AddField(
            model_name='socialmediauser',
            name='social_media_id',
            field=models.CharField(default='', max_length=500, verbose_name='Social Media ID'),
        ),
    ]
