# Generated by Django 4.1.7 on 2023-03-29 20:32

from django.db import migrations, models
import techcomradery_client.models


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_client', '0002_socialmediauser_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('whatsapp', models.CharField(max_length=50, verbose_name='Whatsapp Number')),
                ('linkedin', models.CharField(max_length=500, verbose_name='LinkedIn')),
                ('providing', models.CharField(max_length=50, verbose_name='Providing')),
                ('referral', models.CharField(default=techcomradery_client.models.get_referral, max_length=10, verbose_name='Referral ID')),
            ],
        ),
    ]
