# Generated by Django 4.1.7 on 2023-03-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_client', '0005_alter_subscriptionuser_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
