# Generated by Django 4.1.7 on 2023-03-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_client', '0006_alter_subscriptionuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionuser',
            name='referred_by',
            field=models.CharField(default='', max_length=10, verbose_name='Referred by'),
        ),
    ]
