# Generated by Django 4.1.1 on 2023-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_client', '0007_subscriptionuser_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionuser',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email Sent'),
        ),
    ]
