# Generated by Django 4.1.7 on 2023-03-16 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techcomradery_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_question', models.CharField(max_length=500, verbose_name='Asking Question')),
            ],
        ),
        migrations.CreateModel(
            name='MasterQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Master Question')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('368059e2-01f1-4b82-8b05-7f8f5ddacf11'), primary_key=True, serialize=False, verbose_name='Response ID')),
                ('answer', models.CharField(max_length=1000, verbose_name='User Answer')),
                ('rectify_answer', models.CharField(max_length=1000, verbose_name='Rectify Answer')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 3, 16, 17, 39, 32, 123883), verbose_name='Response Time')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techcomradery_chatbot.askingquestion', verbose_name='Asking Question')),
                ('social_media_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techcomradery_client.socialmediauser', verbose_name='Social Media User')),
            ],
        ),
        migrations.AddField(
            model_name='askingquestion',
            name='master_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techcomradery_chatbot.masterquestion', verbose_name='Parent Question'),
        ),
    ]
