# Generated by Django 4.1.7 on 2023-03-22 09:21

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_chatbot', '0003_alter_userresponse_date_time_alter_userresponse_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequirementDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='BRD ID')),
            ],
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 14, 51, 36, 54734, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Response Time'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Response ID'),
        ),
    ]
