# Generated by Django 4.1.7 on 2023-03-22 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_chatbot', '0004_businessrequirementdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='brd_id',
            field=models.ForeignKey(default='401de6c7-d46f-4fbb-95b1-228c20c81e38', on_delete=django.db.models.deletion.CASCADE, to='techcomradery_chatbot.businessrequirementdocument', verbose_name='BRD_ID'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 14, 52, 49, 730335, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Response Time'),
        ),
    ]
