# Generated by Django 4.1.7 on 2023-03-24 21:08

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_chatbot', '0006_alter_userresponse_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Project ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Project Name')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 3, 25, 2, 38, 17, 111652, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Response Time')),
            ],
        ),
        migrations.AddField(
            model_name='businessrequirementdocument',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 2, 38, 17, 111652, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Response Time'),
        ),
        migrations.AddField(
            model_name='businessrequirementdocument',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='BRD Name'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 2, 38, 17, 111652, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Response Time'),
        ),
    ]
