# Generated by Django 4.1.7 on 2023-03-24 21:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_chatbot', '0008_alter_businessrequirementdocument_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequirementdocument',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='techcomradery_chatbot.project', verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='businessrequirementdocument',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 2, 42, 58, 172083, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 2, 42, 58, 167355, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='brd_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='techcomradery_chatbot.businessrequirementdocument', verbose_name='BRD_ID'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 2, 42, 58, 172083, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Response Time'),
        ),
    ]
