# Generated by Django 4.1.7 on 2023-03-28 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_chatbot', '0009_businessrequirementdocument_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=100, verbose_name='Category Name')),
            ],
        ),
        migrations.AlterField(
            model_name='businessrequirementdocument',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 3, 41, 6, 7715, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 3, 41, 6, 7715, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 3, 41, 6, 16398, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Response Time'),
        ),
        migrations.AddField(
            model_name='masterquestion',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='techcomradery_chatbot.questioncategory', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
