# Generated by Django 4.1.7 on 2023-03-29 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_chatbot', '0011_askingquestion_named_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterquestion',
            name='named_id',
            field=models.CharField(default='0', max_length=10, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='businessrequirementdocument',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 6, 38, 4, 965377, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 6, 38, 4, 965377, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 6, 38, 4, 965377, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Response Time'),
        ),
    ]
