# Generated by Django 4.1.7 on 2023-03-29 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcomradery_chatbot', '0015_alter_businessrequirementdocument_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequirementdocument',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 4, 12, 39, 488728, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 4, 12, 39, 488222, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 4, 12, 39, 488728, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Response Time'),
        ),
    ]
